---
name: CI

'on':
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: Install-PackageProvider -Name "ChocolateyGet" -Force
      - run: Get-PackageSource
      - run: Get-PackageProvider
      - run: Install-Package -AcceptLicense -Force -Name "mdt"