---
name: CI

'on':
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: Install-Package -AcceptLicense -Force -ForceBootstrap -PackageManagementProvider chocolatey -Name "mdt"