---
name: CI

'on':
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: Install-PackageProvider -Force -Name ChocolateyGet
      - run: Import-PackageProvider -Force -Name ChocolateyGet
      - run: Find-Package -Name '*mdt*'
      - run: Install-Package -AcceptLicense -Force -ForceBootstrap -ProviderName ChocolateyGet -Name "mdt"