---
name: CI

'on':
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - run: Find-PackageProvider -Force -ForceBootstrap -IncludeDependencies
      - run: Install-PackageProvider -Force -Name
      - run: Import-PackageProvider -Force -Name 
      - run: Install-Package -AcceptLicense -Force -ForceBootstrap -PackageManagementProvider chocolatey -Name "mdt"